version: '2'

services:
  lamas-frontend:
    build: ./frontend
    env_file: ./frontend/.env
    volumes:
      - ./frontend/src:/app/src

  lamas-backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend/src:/app/src

  redis:
    image: redis
    ports: 
      - 6379:6379
    