version: '2'
services:
  lamas-backend:
    command: npm run start:watch
    stdin_open: true
    volumes:
      - ./src:/app/src
    ports:
      - 4000:8000
    environment:
      - NODE_ENV=development
  lamas-frontend:
    command: npm run start
    stdin_open: true
    volumes:
      - ./lamas-frontend:/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_LAMAS_BACK=http://localhost:${API_PORT}

