name: Automated browser tests
on: [push,pull_request]

jobs:
  tests-backend:
    runs-on: ubuntu-latest
    steps:    
    # 1: setup node
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3: install NPM dependencies
      - name: Install dependencies
        run: cd backend && npm ci
        env: 
          MONGODB_URI_TESTING: ${{ env.MONGODB_URI_TESTING }}

      - name : launch test
        run:  cd backend && npm run test
        env: 
          MONGODB_URI_TESTING: ${{ env.MONGODB_URI_TESTING }}

  tests-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13

      # 2: Checkout repository in the CWD
      - name: Checkout repository
        uses: actions/checkout@v2

      # 3: install NPM dependencies
      - name: Install dependencies
        run: cd frontend && npm install && npm run test
